### ISSUE TITLE
Ability to write out data during processing instead of at end

### ISSUE THREAD

**Issue by phoffer** [jwoertink/sitemapper#32]
Wondering if there is interest in the ability to write files out during the build phase, instead of waiting until the very end. I'm prototyping a replacement for my company's sitemap generation in Ruby, I have it working, but the process grows to 30gb of memory usage on my machine (generating 14.5 million links). 

I played around and got a version working that will write a new file out every time it hits the `@max_urls`, and it kept memory around 300mb for the entire process. It might be a little hacky and have edge cases, but I can make a PR if you'd be interested in it.

**Comment by jwoertink** [comment]
Oh, that's interesting. Yeah, I could see how that could be useful. I think as long as we can keep track of the files so they can be shipped off to S3 or whatever needs to happen, then it should be fine.

**Comment by phoffer** [comment]
Ok awesome. I do keep track of filenames (building index file still works), so I think it would be sufficient. I didn't test the s3 storage class, but I think it would still work. I didn't make any changes to the storage classes. I'll make a PR shortly and can go from there. I haven't added specs yet but it will provide an idea of how (minimally) involved it is.

**Comment by jwoertink** [comment]
Closed by #33
